### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by utkarsh2102** [grosser/fast_gettext#135]
Hello,

Thank you for your work, however one of the test seem to be failing:
```
  1) FastGettext::TranslationRepository::Db expires the cache when updated
     Failure/Error: translation_text.update_attributes :text => 'Autobot'

     NoMethodError:
       undefined method `update_attributes' for #<TranslationText id: 9, text: "Auto", locale: "de", translation_key_id: 6, created_at: "2022-01-18 21:03:12.371243000 +0000", updated_at: "2022-01-18 21:03:12.371243000 +0000">
       Did you mean?  update_attribute
     # /usr/share/rubygems-integration/all/gems/activemodel-6.1.4.1/lib/active_model/attribute_methods.rb:469:in `method_missing'
     # ./spec/fast_gettext/translation_repository/db_spec.rb:115:in `block (2 levels) in <top (required)>'
```

@grosser, any idea what cause this? TIA!

**Comment by utkarsh2102** [comment]
Ah, I know what happened. Simply using `update` instead should work. Want me to raise a PR? :)

**Comment by grosser** [comment]
yes please! :)
