### ISSUE TITLE
Rails 4 Support

### ISSUE THREAD

**Issue by geoffw8** [grosser/fast_gettext#61]
Hey,

I see that in the commits it says "Rails 4 support" but I seem to be getting an error every time I try and start the server from this:

require "fast_gettext/translation_repository/db"

The specific error is:

``` ruby
/Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require': cannot load such file -- protected_attributes (LoadError)
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/fast_gettext-0.8.0/lib/fast_gettext/translation_repository/db_models/translation_key.rb:1:in `<top (required)>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/fast_gettext-0.8.0/lib/fast_gettext/translation_repository/db.rb:52:in `require_models'
    from /Users/geoffmwright/Documents/rails/questionnairely/config/initializers/fast_get_text.rb:2:in `<top (required)>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `block in load'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/engine.rb:608:in `each'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/engine.rb:608:in `block in <class:Engine>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/initializable.rb:44:in `each'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/initializable.rb:44:in `tsort_each_child'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:180:in `each'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
    from /Users/geoffmwright/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/geoffmwright/Documents/rails/questionnairely/config/environment.rb:5:in `<top (required)>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/geoffmwright/Documents/rails/questionnairely/config.ru:3:in `block in <main>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
    from /Users/geoffmwright/Documents/rails/questionnairely/config.ru:in `new'
    from /Users/geoffmwright/Documents/rails/questionnairely/config.ru:in `<main>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/commands/server.rb:48:in `app'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/commands/server.rb:75:in `start'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/commands.rb:78:in `block in <top (required)>'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/commands.rb:73:in `tap'
    from /Users/geoffmwright/.rvm/gems/ruby-1.9.3-p327@questionnaire/gems/railties-4.0.0/lib/rails/commands.rb:73:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Is this to be expected? Has Rails 4 support been fully added? Or is there a fix?

Thanks in advance

**Comment by harisadam** [comment]
Hi @grosser 

I recently made a change that drops support for rails < 4.0. What do you think, should I make a PR or it is a too radical change?
https://github.com/harisadam/fast_gettext/commit/2a7e9e02e5b81a22cc1796896599522c261988bd

a

**Comment by grosser** [comment]
not really against it, but was there anything big breaking ?

**Comment by harisadam** [comment]
well, it works fine with the default Rails stack, but it could cause problems with some gems e.g: [paper_trail](https://github.com/airblade/paper_trail) had conflicts with the protected_attributes gem, that's why I forked your gem few weeks ago

**Comment by grosser** [comment]
let's just kick that out then ...

remove the dependency and add
  attr_accessible :XXXXX if ActiveRecord::VERSION::MAJOR == 3 ||
defined?(ProtectedAttributes)
