### ISSUE TITLE
find_files_in_locale_folders': path locale cound not be found! (RuntimeError)

### ISSUE THREAD

**Issue by JeanOsorio** [grosser/fast_gettext#69]
I trying to create a script in order to create a daemon, but when I try to require my environment with the following line:

```
require File.expand_path("../../../config/environment", __FILE__)
```
I get the following error:

```
/Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext/translation_repository/base.rb:40:in `find_files_in_locale_folders': path locale cound not be found! (RuntimeError)
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext/translation_repository/po.rb:12:in `find_and_store_files'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext/translation_repository/mo.rb:22:in `reload'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext/translation_repository/mo.rb:10:in `initialize'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext/translation_repository.rb:14:in `new'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext/translation_repository.rb:14:in `build'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/fast_gettext-0.8.1/lib/fast_gettext.rb:28:in `add_text_domain'
	from /Users/jeanosorio/repos/blabloo/config/initializers/fast_gettext.rb:1:in `<top (required)>'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `block in load'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/engine.rb:587:in `each'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/engine.rb:587:in `block in <class:Engine>'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
	from /Users/jeanosorio/.rvm/gems/ruby-1.9.3-p484@blabloo/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/jeanosorio/repos/blabloo/config/environment.rb:5:in `<top (required)>'
	from /Users/jeanosorio/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jeanosorio/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from script.rb:5:in `<main>'
```

Does anyone know how to solve this.

Thanks in advance

**Comment by grosser** [comment]
add a `locale` folder, it needs locales to work
